#!/usr/bin/env bash
# 18-disk-alert-setup.sh — disk usage alerting cron
#
# Creates a disk usage monitoring script and daily cron job:
#   - Checks all mounted filesystems
#   - Emails ADMIN_EMAIL when any filesystem exceeds DISK_WARN_PCT (default 80%)
#   - Also checks inode usage (often overlooked)
#   - Cron: daily at 7 AM
#
# Usage:
#   bash scripts/hardening/18-disk-alert-setup.sh
#   bash scripts/hardening/18-disk-alert-setup.sh --dry-run
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root." >&2
    exit 1
fi

# --- Dry-run support ---
DRYRUN=false
for arg in "$@"; do [[ "$arg" == "--dry-run" ]] && DRYRUN=true; done

cmd() {
    if $DRYRUN; then echo "  [dry-run] $*"; return 0; fi
    "$@"
}

# --- Config discovery ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${CONFIG_FILE:-}"
if [[ -z "$CONFIG_FILE" ]]; then
    for loc in \
        "$SCRIPT_DIR/../../config.env" \
        "$SCRIPT_DIR/../config.env" \
        /etc/vps-security/config.env; do
        if [[ -f "$loc" ]]; then CONFIG_FILE="$loc"; break; fi
    done
fi
if [[ -n "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

ADMIN_EMAIL="${ADMIN_EMAIL:-root}"
DISK_WARN_PCT="${DISK_WARN_PCT:-80}"
STEPS=2

echo "========================================="
echo "  Disk Usage Alert Setup"
echo "  Host: $(hostname -f)"
echo "  Date: $(date '+%Y-%m-%d %H:%M %Z')"
echo "========================================="
echo ""

# [1/2] Write disk check script
echo "[1/${STEPS}] Writing disk check script..."

DISK_SCRIPT="/usr/local/sbin/disk-usage-check.sh"

if ! $DRYRUN; then
    cat > "$DISK_SCRIPT" << SCRIPT
#!/usr/bin/env bash
# disk-usage-check.sh — disk and inode usage check with email alert
# Generated by vps-security 18-disk-alert-setup.sh
set -uo pipefail

ADMIN_EMAIL="${ADMIN_EMAIL}"
WARN_PCT="${DISK_WARN_PCT}"
HOSTNAME="\$(hostname -f)"
DATE="\$(date '+%Y-%m-%d %H:%M %Z')"
ALERT=0
ALERT_BODY=""

# Check disk usage (exclude tmpfs, devtmpfs, overlay, squashfs)
while IFS= read -r line; do
    PCT=\$(echo "\$line" | awk '{print \$5}' | tr -d '%')
    MOUNT=\$(echo "\$line" | awk '{print \$6}')
    FS=\$(echo "\$line" | awk '{print \$1}')
    if [[ "\$PCT" -ge "\$WARN_PCT" ]]; then
        ALERT=1
        ALERT_BODY+="\${FS} mounted at \${MOUNT} is \${PCT}% full\n"
    fi
done < <(df -h --output=source,size,used,avail,pcent,target 2>/dev/null | \
    grep -vE "^Filesystem|tmpfs|devtmpfs|overlay|squashfs|udev" | tail -n +2)

# Check inode usage
while IFS= read -r line; do
    PCT=\$(echo "\$line" | awk '{print \$5}' | tr -d '%')
    MOUNT=\$(echo "\$line" | awk '{print \$6}')
    FS=\$(echo "\$line" | awk '{print \$1}')
    if [[ "\$PCT" != "-" ]] && [[ "\$PCT" -ge "\$WARN_PCT" ]] 2>/dev/null; then
        ALERT=1
        ALERT_BODY+="INODES: \${FS} mounted at \${MOUNT} is \${PCT}% full (inode exhaustion)\n"
    fi
done < <(df -i --output=source,itotal,iused,iavail,ipcent,target 2>/dev/null | \
    grep -vE "^Filesystem|tmpfs|devtmpfs|overlay|squashfs|udev" | tail -n +2)

if [[ "\$ALERT" -eq 1 ]]; then
    {
        echo "Disk usage alert on \${HOSTNAME} at \${DATE}"
        echo ""
        printf "%b" "\${ALERT_BODY}"
        echo ""
        echo "Full disk usage:"
        df -h | grep -vE "tmpfs|devtmpfs|overlay|squashfs"
        echo ""
        echo "Inode usage:"
        df -i | grep -vE "tmpfs|devtmpfs|overlay|squashfs"
    } | mail -s "[ALERT] Disk usage warning: \${HOSTNAME}" "\${ADMIN_EMAIL}" 2>/dev/null || true
fi
SCRIPT
    chmod 700 "$DISK_SCRIPT"
    echo "  Written: ${DISK_SCRIPT}"
else
    echo "  [dry-run] Would write: ${DISK_SCRIPT}"
fi

# [2/2] Schedule daily cron
echo "[2/${STEPS}] Scheduling daily disk check..."

if $DRYRUN; then
    echo "  [dry-run] Would write: /etc/cron.d/disk-usage-check"
else
    cat > /etc/cron.d/disk-usage-check << CRON
# vps-security: daily disk usage check (7 AM)
0 7 * * * root ${DISK_SCRIPT}
CRON
    chmod 644 /etc/cron.d/disk-usage-check
    echo "  Cron scheduled: daily 7 AM -> alerts to ${ADMIN_EMAIL}"
fi

echo ""
echo "========================================="
echo "  Disk alert setup complete."
echo ""
echo "  Script: ${DISK_SCRIPT}"
echo "  Cron:   daily 7 AM"
echo "  Alert:  ${ADMIN_EMAIL} when any FS > ${DISK_WARN_PCT}%"
echo ""
echo "  Test now: bash ${DISK_SCRIPT}"
echo "  Override threshold: DISK_WARN_PCT=70 in config.env"
echo "========================================="
